---
#gem|yum| install mkpasswd
#apt-get install -y whois
#generate new password -->  mkpasswd --method=sha-512


- name: create user and make sudo
  hosts: all
  vars_prompt:
    - name: username
      prompt: What is your username?
      private: false
      #default: ""
    - name: password
      #default: ""
      prompt: What is your password?

  tasks:
    - name: Create a login user
      user:
        name: "{{ username }}"
        password: "{{ password }}"
        groups:
         - sudo
        state: present
        shell: /bin/bash       # Defaults to /bin/bash
        system: no             # Defaults to no
        createhome: yes        # Defaults to yes
        home: /home/{{ username }}  # Defaults to /home/<username>

    - name: Print a message
      ansible.builtin.debug:
        msg: 'Logging in as {{ username }} {{ password  }}'


    - name: Make sudo without password for {{ username }} user
      copy:
        dest: /etc/sudoers.d/80-ansible-sudo-user
        #content: "{{ username }} ALL=(ALL) NOPASSWD:ALL"
        content: "{{ username }} ALL=(ALL) ALL"
        mode: 0440
